#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE=".env.local"

# Keep captured values out of git before anything is written.
if ! grep -qsE '^\.env' .gitignore 2>/dev/null; then
  printf '.env*\n' >> .gitignore
fi

banner "Trailhead: Supabase project + Google OAuth (gmail.readonly)"

# ── Stage 1: Supabase project ─────────────────────────────────────────────
stage "Supabase: create the trailhead project"
say "Per ADR 0001 this is a fresh project, not a reuse of flight-scanner."
open_url "https://supabase.com/dashboard/new"
step "New project → name: trailhead → region: Central EU (Frankfurt) / eu-central-1."
step "Generate a strong database password and save it in your password manager."
step "Create the project, then look at the browser URL:"
note "  https://supabase.com/dashboard/project/<PROJECT_REF>  ← the ref is that last segment"
ask SUPABASE_PROJECT_REF "Paste the project ref:"
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
write_env NEXT_PUBLIC_SUPABASE_URL "https://${SUPABASE_PROJECT_REF}.supabase.co"

# ── Stage 2: Google Cloud project ─────────────────────────────────────────
stage "Google Cloud: create the project"
open_url "https://console.cloud.google.com/projectcreate"
step "Project name: trailhead (Google will suggest a project ID — you can keep it)."
step "Create, wait for the notification, and make sure the new project is selected"
say "  in the console's top project picker."
ask GOOGLE_CLOUD_PROJECT "Paste the project ID (not the name):"
write_env GOOGLE_CLOUD_PROJECT "$GOOGLE_CLOUD_PROJECT"

# ── Stage 3: enable the Gmail API ─────────────────────────────────────────
stage "Google Cloud: enable the Gmail API"
open_url "https://console.cloud.google.com/apis/library/gmail.googleapis.com?project=${GOOGLE_CLOUD_PROJECT}"
step "Click Enable and wait for it to finish."
note "If the page looks different from these instructions anywhere in this"
note "wizard, Google moved it — use the console search box for the page name."
pause "Enabled?"

# ── Stage 4: consent screen (Testing mode) ────────────────────────────────
stage "Google Auth platform: branding + audience"
open_url "https://console.cloud.google.com/auth/branding?project=${GOOGLE_CLOUD_PROJECT}"
step "If prompted to configure the consent screen: app name Trailhead,"
say "  support email = your Gmail, audience External, add your email as the"
say "  developer contact, and finish."
step "Otherwise set those fields on the Branding page and save."
open_url "https://console.cloud.google.com/auth/audience?project=${GOOGLE_CLOUD_PROJECT}"
step "On Audience: confirm User type External and Publishing status Testing."
warn "Stay in Testing. Publishing unverified triggers a lifetime 100-user cap"
warn "(see tracker/tickets/004-gmail-access-and-verification.md)."
pause "Branding saved and status is Testing?"

# ── Stage 5: request the gmail.readonly scope ─────────────────────────────
stage "Google Auth platform: add the gmail.readonly scope"
open_url "https://console.cloud.google.com/auth/scopes?project=${GOOGLE_CLOUD_PROJECT}"
step "Data Access → Add or remove scopes → filter for gmail.readonly."
step "Tick https://www.googleapis.com/auth/gmail.readonly (it is listed under"
say "  restricted scopes), then Update and Save."
note "In Testing mode this needs no verification — testers just see an"
note "'unverified app' interstitial they can click through."
pause "Scope added and saved?"

# ── Stage 6: test users ───────────────────────────────────────────────────
stage "Google Auth platform: add test users"
open_url "https://console.cloud.google.com/auth/audience?project=${GOOGLE_CLOUD_PROJECT}"
step "Under Test users → Add users: add your own Gmail address (the mailbox"
say "  Trailhead will read), plus any other testers (max 100)."
note "Testing-mode consents expire every 7 days — weekly re-consent is normal."
pause "Test users added?"

# ── Stage 7: OAuth client ─────────────────────────────────────────────────
stage "Google Auth platform: create the OAuth client"
say "Supabase Auth is the OAuth callback target (ADR 0001), so the client"
say "points at your Supabase project:"
open_url "https://console.cloud.google.com/auth/clients?project=${GOOGLE_CLOUD_PROJECT}"
step "Create client → Application type: Web application → name: Trailhead (Supabase Auth)."
step "Authorized JavaScript origins — add both:"
say "    https://${SUPABASE_PROJECT_REF}.supabase.co"
say "    http://localhost:3000"
step "Authorized redirect URIs — add:"
say "    https://${SUPABASE_PROJECT_REF}.supabase.co/auth/v1/callback"
step "Create, then copy the Client ID and Client secret from the dialog."
ask GOOGLE_OAUTH_CLIENT_ID "Paste the client ID:"
ask_secret GOOGLE_OAUTH_CLIENT_SECRET "Paste the client secret (hidden):"
write_env GOOGLE_OAUTH_CLIENT_ID "$GOOGLE_OAUTH_CLIENT_ID"
write_env GOOGLE_OAUTH_CLIENT_SECRET "$GOOGLE_OAUTH_CLIENT_SECRET"

# ── Stage 8: wire the client into Supabase Auth ───────────────────────────
stage "Supabase: enable the Google provider"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/providers"
step "Open the Google provider → Enable it."
step "Paste the Client ID and Client secret from the previous stage."
step "Check the 'Callback URL' Supabase displays on that panel:"
say "  it must equal https://${SUPABASE_PROJECT_REF}.supabase.co/auth/v1/callback."
warn "If Supabase shows a different callback URL, go back to the Google client"
warn "and replace the redirect URI with exactly what Supabase displays."
step "Save."
pause "Provider enabled and saved?"

finish
note "Record for the tracker: project IDs are in .env.local; the client secret"
note "also lives in Supabase's Google provider config. Nothing was pushed to CI."
